import { Puzzle } from "./types";

export const GALLERY_PUZZLES: Puzzle[] = [
  {
    id: "cozy-cottage",
    title: "Cozy Cottage Stream",
    artist: "@PixelArtist_Cat",
    pieces: 24, // Optimized for responsive co-op play
    difficulty: "Medium",
    category: "Retro Landscapes",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    description: "A warm and peaceful cottage by a babbling brook under twilight skies.",
    rows: 4,
    cols: 6,
    activePlayersCount: 42,
  },
  {
    id: "cyber-neon-city",
    title: "Retro Cyber Neon City",
    artist: "@VaporWave_99",
    pieces: 30,
    difficulty: "Hard",
    category: "Pixel Art",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    description: "Vibrant neon skyscrapers shining through rain-slicked cyberpunk alleyways.",
    rows: 5,
    cols: 6,
    activePlayersCount: 88,
  },
  {
    id: "sunset-coffee-bakery",
    title: "Sunset Coffee Bakery",
    artist: "@Mochi_Baker",
    pieces: 20,
    difficulty: "Easy",
    category: "Coffee & Bakery",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    description: "Fresh warm croissants, steaming matcha lattes, and golden hour light.",
    rows: 4,
    cols: 5,
    activePlayersCount: 19,
  },
  {
    id: "magical-forest-shrine",
    title: "Magical Forest Shrine",
    artist: "@GhibliVibes",
    pieces: 24,
    difficulty: "Medium",
    category: "Cozy Illustrations",
    imageUrl: "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80",
    description: "Ancient stone torii gate overgrown with lush moss and playful spirit wisps.",
    rows: 4,
    cols: 6,
    activePlayersCount: 54,
  },
  {
    id: "pixel-cat-cafe",
    title: "Sleepy Pixel Kittens",
    artist: "@NekoPurr",
    pieces: 16,
    difficulty: "Easy",
    category: "Cute Animals",
    imageUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80",
    description: "Trio of adorable cats napping peacefully in sunlit wicker baskets.",
    rows: 4,
    cols: 4,
    activePlayersCount: 31,
  },
  {
    id: "starlight-observatory",
    title: "Starlight Mountain Trail",
    artist: "@RetroAstro",
    pieces: 30,
    difficulty: "Hard",
    category: "Retro Landscapes",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    description: "Majestic alpine peaks reflecting the cosmic glow of the Milky Way.",
    rows: 5,
    cols: 6,
    activePlayersCount: 63,
  },
];
